In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

In [5]:
paths={
    "circuits":"circuits.csv",
    "constructors":"constructors.csv",
    "constructor_results":"constructor_results.csv",
    "constructors":"constructors.csv",
    "driver_standings":"driver_standings.csv",
    "drivers":"drivers.csv",
    "lap_times":"lap_times.csv",
    "pit_stops":"pit_stops.csv",
    "qualifying":"qualifying.csv",
    "races":"races.csv",
    "results":"results.csv",
    "seasons":"seasons.csv",
    "sprint_results":"sprint_results.csv",
    "status":"status.csv"
}

In [6]:
df={
    name:pd.read_csv(path) for name,path in paths.items()
}
df

{'circuits':     circuitId   circuitRef                                  name  \
 0           1  albert_park        Albert Park Grand Prix Circuit
 1           2       sepang          Sepang International Circuit
 2           3      bahrain         Bahrain International Circuit
 3           4    catalunya        Circuit de Barcelona-Catalunya
 4           5     istanbul                         Istanbul Park
 ..        ...          ...                                   ...
 72         75     portimao    Autódromo Internacional do Algarve
 73         76      mugello  Autodromo Internazionale del Mugello
 74         77       jeddah               Jeddah Corniche Circuit
 75         78       losail          Losail International Circuit
 76         79        miami         Miami International Autodrome

         location       country       lat        lng  alt  \
 0      Melbourne     Australia -37.84970  144.96800   10
 1   Kuala Lumpur      Malaysia   2.76083  101.73800   18
 2         Sakhir       Bahrain  26.03250   50.51060    7
 3       Montmeló         Spain  41.57000    2.26111  109
 4       Istanbul        Turkey  40.95170   29.40500  130
 ..           ...           ...       ...        ...  ...
 72      Portimão      Portugal  37.22700   -8.62670  108
 73       Mugello         Italy  43.99750   11.37190  255
 74        Jeddah  Saudi Arabia  21.63190   39.10440   15
 75     Al Daayen         Qatar  25.49000   51.45420   12
 76         Miami           USA  25.95810  -80.23890    0

                                                   url
 0   http://en.wikipedia.org/wiki/Melbourne_Grand_P...
 1   http://en.wikipedia.org/wiki/Sepang_Internatio...
 2   http://en.wikipedia.org/wiki/Bahrain_Internati...
 3   http://en.wikipedia.org/wiki/Circuit_de_Barcel...
 4          http://en.wikipedia.org/wiki/Istanbul_Park
 ..                                                ...
 72  http://en.wikipedia.org/wiki/Algarve_Internati...
 73       http://en.wikipedia.org/wiki/Mugello_Circuit
 74  http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
 75  http://en.wikipedia.org/wiki/Losail_Internatio...
 76  http://en.wikipedia.org/wiki/Miami_Internation...

 [77 rows x 9 columns],
 'constructors':      constructorId constructorRef            name nationality  \
 0                1        mclaren         McLaren     British
 1                2     bmw_sauber      BMW Sauber      German
 2                3       williams        Williams     British
 3                4        renault         Renault      French
 4                5     toro_rosso      Toro Rosso     Italian
 ..             ...            ...             ...         ...
 207            210           haas    Haas F1 Team    American
 208            211   racing_point    Racing Point     British
 209            213     alphatauri      AlphaTauri     Italian
 210            214         alpine  Alpine F1 Team      French
 211            215             rb      RB F1 Team     Italian

                                                    url
 0                 http://en.wikipedia.org/wiki/McLaren
 1              http://en.wikipedia.org/wiki/BMW_Sauber
 2    http://en.wikipedia.org/wiki/Williams_Grand_Pr...
 3    http://en.wikipedia.org/wiki/Renault_in_Formul...
 4     http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
 ..                                                 ...
 207          http://en.wikipedia.org/wiki/Haas_F1_Team
 208  http://en.wikipedia.org/wiki/Racing_Point_F1_Team
 209   http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
 210        http://en.wikipedia.org/wiki/Alpine_F1_Team
 211   http://en.wikipedia.org/wiki/RB_Formula_One_Team

 [212 rows x 5 columns],
 'constructor_results':        constructorResultsId  raceId  constructorId  points status
 0                         1      18              1    14.0     \N
 1                         2      18              2     8.0     \N
 2                         3      18              3     9.0     \N
 3                         4      18              4     5.0     \N
 4                         5      18              5     2.0     \N
 ...                     ...     ...            ...     ...    ...
 12620                 17125    1144            210     4.0     \N
 12621                 17126    1144            117     2.0     \N
 12622                 17127    1144              3     0.0     \N
 12623                 17128    1144            215     0.0     \N
 12624                 17129    1144             15     0.0     \N

 [12625 rows x 5 columns],
 'driver_standings':        driverStandingsId  raceId  driverId  points  position positionText  \
 0                      1      18         1    10.0         1            1
 1                      2      18         2     8.0         2            2
 2                      3      18         3     6.0         3            3
 3                      4      18         4     5.0         4            4
 4                      5      18         5     4.0         5            5
 ...                  ...     ...       ...     ...       ...          ...
 34858              73266    1144       858     0.0        23           23
 34859              73267    1144       860     7.0        18           18
 34860              73268    1144       861     5.0        19           19
 34861              73269    1144       859     4.0        21           21
 34862              73270    1144       862     0.0        24           24

        wins
 0         1
 1         0
 2         0
 3         0
 4         0
 ...     ...
 34858     0
 34859     0
 34860     0
 34861     0
 34862     0

 [34863 rows x 7 columns],
 'drivers':      driverId   driverRef number code  forename     surname         dob  \
 0           1    hamilton     44  HAM     Lewis    Hamilton  1985-01-07
 1           2    heidfeld     \N  HEI      Nick    Heidfeld  1977-05-10
 2           3     rosberg      6  ROS      Nico     Rosberg  1985-06-27
 3           4      alonso     14  ALO  Fernando      Alonso  1981-07-29
 4           5  kovalainen     \N  KOV    Heikki  Kovalainen  1981-10-19
 ..        ...         ...    ...  ...       ...         ...         ...
 856       858    sargeant      2  SAR     Logan    Sargeant  2000-12-31
 857       859      lawson     30  LAW      Liam      Lawson  2002-02-11
 858       860     bearman     38  BEA    Oliver     Bearman  2005-05-08
 859       861   colapinto     43  COL    Franco   Colapinto  2003-05-27
 860       862      doohan     61  DOO      Jack      Doohan  2003-01-20

        nationality                                             url
 0          British     http://en.wikipedia.org/wiki/Lewis_Hamilton
 1           German      http://en.wikipedia.org/wiki/Nick_Heidfeld
 2           German       http://en.wikipedia.org/wiki/Nico_Rosberg
 3          Spanish    http://en.wikipedia.org/wiki/Fernando_Alonso
 4          Finnish  http://en.wikipedia.org/wiki/Heikki_Kovalainen
 ..             ...                                             ...
 856       American     http://en.wikipedia.org/wiki/Logan_Sargeant
 857  New Zealander        http://en.wikipedia.org/wiki/Liam_Lawson
 858        British     http://en.wikipedia.org/wiki/Oliver_Bearman
 859   Argentinian    http://en.wikipedia.org/wiki/Franco_Colapinto
 860     Australian        http://en.wikipedia.org/wiki/Jack_Doohan

 [861 rows x 9 columns],
 'lap_times':         raceId  driverId  lap  position      time  milliseconds
 0          841        20    1         1  1:38.109         98109
 1          841        20    2         1  1:33.006         93006
 2          841        20    3         1  1:32.713         92713
 3          841        20    4         1  1:32.803         92803
 4          841        20    5         1  1:32.342         92342
 ...        ...       ...  ...       ...       ...           ...
 589076    1144       857   54        10  1:27.731         87731
 589077    1144       857   55        10  1:27.781         87781
 589078    1144       857   56        10  1:27.816         87816
 589079    1144       857   57        10  1:28.554         88554
 589080    1144       857   58        10  1:28.010         88010

 [589081 rows x 6 columns],
 'pit_stops':        raceId  driverId  stop  lap      time duration  milliseconds
 0         841       153     1    1  17:05:23   26.898         26898
 1         841        30     1    1  17:05:52   25.021         25021
 2         841        17     1   11  17:20:48   23.426         23426
 3         841         4     1   12  17:22:34   23.251         23251
 4         841        13     1   13  17:24:10   23.842         23842
 ...       ...       ...   ...  ...       ...      ...           ...
 11366    1144       840     2   32  17:52:48   22.053         22053
 11367    1144         1     1   34  17:55:17   21.694         21694
 11368    1144         4     2   37  18:00:10   22.437         22437
 11369    1144       855     2   39  18:03:21   28.765         28765
 11370    1144       825     4   55  18:28:06   22.090         22090

 [11371 rows x 7 columns],
 'qualifying':        qualifyId  raceId  driverId  constructorId  number  position        q1  \
 0              1      18         1              1      22         1  1:26.572
 1              2      18         9              2       4         2  1:26.103
 2              3      18         5              1      23         3  1:25.664
 3              4      18        13              6       2         4  1:25.994
 4              5      18         2              2       3         5  1:25.960
 ...          ...     ...       ...            ...     ...       ...       ...
 10489      10547    1144       848              3      23        16  1:23.821
 10490      10548    1144       855             15      24        17  1:23.880
 10491      10549    1144         1            131      44        18  1:23.887
 10492      10550    1144       861              3      43        19  1:23.912
 10493      10551    1144       862            214      61        20  1:24.105

              q2        q3
 0      1:25.187  1:26.714
 1      1:25.315  1:26.869
 2      1:25.452  1:27.079
 3      1:25.691  1:27.178
 4      1:25.518  1:27.236
 ...         ...       ...
 10489        \N        \N
 10490        \N        \N
 10491        \N        \N
 10492        \N        \N
 10493        \N        \N

 [10494 rows x 9 columns],
 'races':       raceId  year  round  circuitId                    name        date  \
 0          1  2009      1          1   Australian Grand Prix  2009-03-29
 1          2  2009      2          2    Malaysian Grand Prix  2009-04-05
 2          3  2009      3         17      Chinese Grand Prix  2009-04-19
 3          4  2009      4          3      Bahrain Grand Prix  2009-04-26
 4          5  2009      5          4      Spanish Grand Prix  2009-05-10
 ...      ...   ...    ...        ...                     ...         ...
 1120    1140  2024     20         32  Mexico City Grand Prix  2024-10-27
 1121    1141  2024     21         18    São Paulo Grand Prix  2024-11-03
 1122    1142  2024     22         80    Las Vegas Grand Prix  2024-11-23
 1123    1143  2024     23         78        Qatar Grand Prix  2024-12-01
 1124    1144  2024     24         24    Abu Dhabi Grand Prix  2024-12-08

           time                                                url    fp1_date  \
 0     06:00:00  http://en.wikipedia.org/wiki/2009_Australian_G...          \N
 1     09:00:00  http://en.wikipedia.org/wiki/2009_Malaysian_Gr...          \N
 2     07:00:00  http://en.wikipedia.org/wiki/2009_Chinese_Gran...          \N
 3     12:00:00  http://en.wikipedia.org/wiki/2009_Bahrain_Gran...          \N
 4     12:00:00  http://en.wikipedia.org/wiki/2009_Spanish_Gran...          \N
 ...        ...                                                ...         ...
 1120  20:00:00  https://en.wikipedia.org/wiki/2024_Mexico_City...  2024-10-25
 1121  17:00:00  https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...  2024-11-01
 1122  06:00:00  https://en.wikipedia.org/wiki/2024_Las_Vegas_G...  2024-11-21
 1123  17:00:00  https://en.wikipedia.org/wiki/2024_Qatar_Grand...  2024-11-29
 1124  13:00:00  https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...  2024-12-06

       fp1_time    fp2_date  fp2_time    fp3_date  fp3_time  quali_date  \
 0           \N          \N        \N          \N        \N          \N
 1           \N          \N        \N          \N        \N          \N
 2           \N          \N        \N          \N        \N          \N
 3           \N          \N        \N          \N        \N          \N
 4           \N          \N        \N          \N        \N          \N
 ...        ...         ...       ...         ...       ...         ...
 1120  18:30:00  2024-10-25  22:00:00  2024-10-26  17:30:00  2024-10-26
 1121  14:30:00  2024-11-01  18:30:00          \N        \N  2024-11-02
 1122  02:30:00  2024-11-21  06:00:00  2024-11-22  02:30:00  2024-11-22
 1123  13:30:00  2024-11-29  17:30:00          \N        \N  2024-11-30
 1124  09:30:00  2024-12-06  13:00:00  2024-12-07  10:30:00  2024-12-07

      quali_time sprint_date sprint_time
 0            \N          \N          \N
 1            \N          \N          \N
 2            \N          \N          \N
 3            \N          \N          \N
 4            \N          \N          \N
 ...         ...         ...         ...
 1120   21:00:00          \N          \N
 1121   18:00:00  2024-11-02    14:00:00
 1122   06:00:00          \N          \N
 1123   17:00:00  2024-11-30    13:00:00
 1124   14:00:00          \N          \N

 [1125 rows x 18 columns],
 'results':        resultId  raceId  driverId  constructorId number  grid position  \
 0             1      18         1              1     22     1        1
 1             2      18         2              2      3     5        2
 2             3      18         3              3      7     7        3
 3             4      18         4              4      5    11        4
 4             5      18         5              1     23     3        5
 ...         ...     ...       ...            ...    ...   ...      ...
 26754     26760    1144       825            210     20    14       16
 26755     26761    1144       859            215     30    12       17
 26756     26762    1144       822             15     77     9       \N
 26757     26763    1144       861              3     43    20       \N
 26758     26764    1144       815              9     11    10       \N

       positionText  positionOrder  points  laps         time milliseconds  \
 0                1              1    10.0    58  1:34:50.616      5690616
 1                2              2     8.0    58       +5.478      5696094
 2                3              3     6.0    58       +8.163      5698779
 3                4              4     5.0    58      +17.181      5707797
 4                5              5     4.0    58      +18.014      5708630
 ...            ...            ...     ...   ...          ...          ...
 26754           16             16     0.0    57           \N           \N
 26755           17             17     0.0    55           \N           \N
 26756            R             18     0.0    30           \N           \N
 26757            R             19     0.0    26           \N           \N
 26758            R             20     0.0     0           \N           \N

       fastestLap rank fastestLapTime fastestLapSpeed  statusId
 0             39    2       1:27.452         218.300         1
 1             41    3       1:27.739         217.586         1
 2             41    5       1:28.090         216.719         1
 3             58    7       1:28.603         215.464         1
 4             43    1       1:27.418         218.385         1
 ...          ...  ...            ...             ...       ...
 26754         57    1       1:25.637         222.002        11
 26755         52   12       1:28.751         214.212         5
 26756         14   19       1:29.482         212.462       130
 26757          5   17       1:29.411         212.631         5
 26758         \N    0             \N              \N         4

 [26759 rows x 18 columns],
 'seasons':     year                                                url
 0   2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
 1   2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
 2   2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
 3   2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
 4   2005  http://en.wikipedia.org/wiki/2005_Formula_One_...
 ..   ...                                                ...
 70  2020  http://en.wikipedia.org/wiki/2020_Formula_One_...
 71  2021  http://en.wikipedia.org/wiki/2021_Formula_One_...
 72  2022  http://en.wikipedia.org/wiki/2022_Formula_One_...
 73  2023  http://en.wikipedia.org/wiki/2023_Formula_One_...
 74  2024  https://en.wikipedia.org/wiki/2024_Formula_One...

 [75 rows x 2 columns],
 'sprint_results':      resultId  raceId  driverId  constructorId  number  grid position  \
 0           1    1061       830              9      33     2        1
 1           2    1061         1            131      44     1        2
 2           3    1061       822            131      77     3        3
 3           4    1061       844              6      16     4        4
 4           5    1061       846              1       4     6        5
 ..        ...     ...       ...            ...     ...   ...      ...
 355       356    1143       859            215      30    10       16
 356       357    1143       852            215      22    16       17
 357       358    1143       861              3      43     0       18
 358       359    1143       855             15      24    18       19
 359       360    1143       815              9      11     0       20

     positionText  positionOrder  points  laps       time milliseconds  \
 0              1              1       3    17  25:38.426      1538426
 1              2              2       2    17     +1.430      1539856
 2              3              3       1    17     +7.502      1545928
 3              4              4       0    17    +11.278      1549704
 4              5              5       0    17    +24.111      1562537
 ..           ...            ...     ...   ...        ...          ...
 355           16             16       0    19    +34.356      1657366
 356           17             17       0    19    +35.102      1658112
 357           18             18       0    19    +35.639      1658649
 358           19             19       0    19  +1:11.436      1694446
 359           20             20       0    19  +1:14.371      1697381

     fastestLap fastestLapTime  statusId
 0           14       1:30.013         1
 1           17       1:29.937         1
 2           17       1:29.958         1
 3           16       1:30.163         1
 4           16       1:30.566         1
 ..         ...            ...       ...
 355         18       1:25.762         1
 356         17       1:25.838         1
 357         18       1:25.599         1
 358         19       1:25.051         1
 359         18       1:24.892         1

 [360 rows x 16 columns],
 'status':      statusId          status
 0           1        Finished
 1           2    Disqualified
 2           3        Accident
 3           4       Collision
 4           5          Engine
 ..        ...             ...
 134       137          Damage
 135       138          Debris
 136       139         Illness
 137       140       Undertray
 138       141  Cooling system

 [139 rows x 2 columns]}

In [7]:
master_df=df["results"].merge(
    df['drivers'],
    on="driverId",
    how="left"
)

In [8]:
master_df=master_df.merge(
    df['constructors'],
    on="constructorId",
    how="left"
)

In [9]:
master_df=master_df.merge(
    df['races'],
    on="raceId",
    how="left"
)

In [10]:
df['circuits'].columns.tolist()

['circuitId',
 'circuitRef',
 'name',
 'location',
 'country',
 'lat',
 'lng',
 'alt',
 'url']

In [11]:
circuits_df=df['circuits'].drop(columns=['url'],errors='ignore')

In [12]:
master_df=master_df.merge(
   circuits_df,
   on="circuitId",
   how="left"
)

In [13]:
master_df=master_df.loc[:,~master_df.columns.duplicated()]

In [14]:
from ydata_profiling import ProfileReport as pr

In [30]:
profile=pr(master_df,title="Master Df report",explorative=True).to_file("project.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 43/43 [00:01<00:00, 42.99it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
master_df.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number_x', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time_x',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driverRef', 'number_y', 'code',
       'forename', 'surname', 'dob', 'nationality_x', 'url_x',
       'constructorRef', 'name_x', 'nationality_y', 'url_y', 'year', 'round',
       'circuitId', 'name_y', 'date', 'time_y', 'url', 'fp1_date', 'fp1_time',
       'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date',
       'quali_time', 'sprint_date', 'sprint_time', 'circuitRef', 'name',
       'location', 'country', 'lat', 'lng', 'alt'],
      dtype='object')

In [17]:
master_df=master_df.rename(columns={
    'name_x':'constructor_name',
    'name_y':'race_name',
    'name':'circuit_name',
    'nationality_x':'driver_nationality',
    'nationality_y':'constructors_nationality',
    'number_x':'race_number',
    'number_y':'driver_number',
    'url_x':'driver_url',
    'url_y':'constructor_url'
}
)

In [18]:
master_df

,resultId,raceId,driverId,constructorId,race_number,grid,position,positionText,positionOrder,points,...,quali_time,sprint_date,sprint_time,circuitRef,circuit_name,location,country,lat,lng,alt
0,1,18,1,1,22,1,1,1,1,10.0,...,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10
1,2,18,2,2,3,5,2,2,2,8.0,...,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10
2,3,18,3,3,7,7,3,3,3,6.0,...,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10
3,4,18,4,4,5,11,4,4,4,5.0,...,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10
4,5,18,5,1,23,3,5,5,5,4.0,...,\N,\N,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,...,14:00:00,\N,\N,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3
26755,26761,1144,859,215,30,12,17,17,17,0.0,...,14:00:00,\N,\N,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3
26756,26762,1144,822,15,77,9,\N,R,18,0.0,...,14:00:00,\N,\N,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3
26757,26763,1144,861,3,43,20,\N,R,19,0.0,...,14:00:00,\N,\N,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3
26758,26764,1144,815,9,11,10,\N,R,20,0.0,...,14:00:00,\N,\N,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3

In [19]:
master_df.head().style.set_table_attributes("style='display:inline'").set_caption("preview of master df")

In [20]:
if "time_y" in master_df.columns:
    master_df['race_datetime']=pd.to_datetime(
        master_df['date'].astype(str)+' '+master_df['time_y'].fillna(''),
        errors='coerce'
    )

In [21]:
drop_cols=[
    'fp1_date','fp1_time','fp2_date','fp2_time',
    'fp3_date','fp3_time','quali_date','quali_time',
    'sprint_date','sprint_time','driver_url','constructor_url'
]
master_df=master_df.drop(columns=[c for c in drop_cols if c in master_df.columns])

In [22]:
master_df=master_df.sort_values(['year','round','positionOrder']).reset_index(drop=True)

In [23]:
analysis_df = master_df[[
    'year', 'round', 'race_name', 'circuit_name', 'location', 'country',
    'driverId', 'forename', 'surname', 'driver_nationality',
    'constructor_name', 'constructors_nationality',
    'grid', 'positionOrder', 'points', 'laps',
    'fastestLap', 'fastestLapTime', 'fastestLapSpeed'
]]

In [24]:
analysis_df.head().style.set_table_attributes("style='display:inline'").set_caption("fresh table")

In [25]:
analysis_df['Drive name']=analysis_df['forename']+' '+analysis_df['surname']
analysis_df=analysis_df.drop(columns=['forename','surname'])
analysis_df

/var/folders/cs/zbb65lfn07gb2dyqtysq1vgm0000gn/T/ipykernel_8933/408788441.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  analysis_df['Drive name']=analysis_df['forename']+' '+analysis_df['surname']

,year,round,race_name,circuit_name,location,country,driverId,driver_nationality,constructor_name,constructors_nationality,grid,positionOrder,points,laps,fastestLap,fastestLapTime,fastestLapSpeed,Drive name
0,1950,1,British Grand Prix,Silverstone Circuit,Silverstone,UK,642,Italian,Alfa Romeo,Swiss,1,1,9.0,70,\N,\N,\N,Nino Farina
1,1950,1,British Grand Prix,Silverstone Circuit,Silverstone,UK,786,Italian,Alfa Romeo,Swiss,2,2,6.0,70,\N,\N,\N,Luigi Fagioli
2,1950,1,British Grand Prix,Silverstone Circuit,Silverstone,UK,686,British,Alfa Romeo,Swiss,4,3,4.0,70,\N,\N,\N,Reg Parnell
3,1950,1,British Grand Prix,Silverstone Circuit,Silverstone,UK,704,French,Talbot-Lago,French,6,4,3.0,68,\N,\N,\N,Yves Cabantous
4,1950,1,British Grand Prix,Silverstone Circuit,Silverstone,UK,627,French,Talbot-Lago,French,9,5,2.0,68,\N,\N,\N,Louis Rosier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,2024,24,Abu Dhabi Grand Prix,Yas Marina Circuit,Abu Dhabi,UAE,825,Danish,Haas F1 Team,American,14,16,0.0,57,57,1:25.637,222.002,Kevin Magnussen
26755,2024,24,Abu Dhabi Grand Prix,Yas Marina Circuit,Abu Dhabi,UAE,859,New Zealander,RB F1 Team,Italian,12,17,0.0,55,52,1:28.751,214.212,Liam Lawson
26756,2024,24,Abu Dhabi Grand Prix,Yas Marina Circuit,Abu Dhabi,UAE,822,Finnish,Sauber,Swiss,9,18,0.0,30,14,1:29.482,212.462,Valtteri Bottas
26757,2024,24,Abu Dhabi Grand Prix,Yas Marina Circuit,Abu Dhabi,UAE,861,Argentinian,Williams,British,20,19,0.0,26,5,1:29.411,212.631,Franco Colapinto
26758,2024,24,Abu Dhabi Grand Prix,Yas Marina Circuit,Abu Dhabi,UAE,815,Mexican,Red Bull,Austrian,10,20,0.0,0,\N,\N,\N,Sergio Pérez

In [26]:
analysis_df=analysis_df[[
        'year', 'round', 'race_name', 'circuit_name', 'location', 'country',
        'driverId','Drive name','driver_nationality',
        'constructor_name', 'constructors_nationality',
        'grid', 'positionOrder', 'points', 'laps',
        'fastestLap', 'fastestLapTime', 'fastestLapSpeed'
]]
analysis_df.head().style.set_table_attributes("style='display:inline;background-color=red'").set_caption("my new table")

In [27]:
analysis_df.to_csv("Cleaned_table_part_one.csv")